### ISSUE TITLE
Unrecognized relative link warning with nav cross links

### ISSUE THREAD

**Issue by wtjones** [oprypin/mkdocs-literate-nav#32] opened 2024-05-03 19:50 UTC
I have this in `docs/SUMMARY.md`:

```
* [Architecture](arch/)
```

The target folder contains a `SUMMARY.md` file per the [nav cross-link](https://github.com/oprypin/mkdocs-literate-nav?tab=readme-ov-file#nav-cross-link) feature. Everything works fine, however I get this message:

> Doc file 'SUMMARY.md' contains an unrecognized relative link 'arch/', it was left as is. Did you mean 'arch/index.md'?

Mkdocs wants me to put `arch/index.md` for the sake of [raw md navigation](https://www.mkdocs.org/user-guide/configuration/#validation-of-absolute-links), but that trips up the plugin and will not render the nav. I can configure the warnings to be ignored, but was checking for a cleaner solution.

**Comment by oprypin** [comment] 2024-05-03 19:56
See https://github.com/oprypin/mkdocs-literate-nav/issues/28#issuecomment-1848397051

Duplicate of #28

**Closed by oprypin** 2024-05-03 19:56 UTC
